### ISSUE TITLE
Missing "Payment Method" in Transaction Report admin emails

### ISSUE THREAD

**Issue by ablears** [webaware/dps-pxpay-for-wp-ecommerce#1]
Thanks for writing this plugin. I'm testing it and everything's good except the payment method in the transaction report admin email is blank. 

Sample email:

> Transaction  Details
> Sale Log ID: Purchase # 5476
> 
> Transaction ID: 0000000324032a84
> Subtotal: $59.00
> Tax: $0.00
> Shipping: $0.00
> Total: $59.00
> Payment Method:

**Comment by webaware** [comment]
I've investigated this, and found that _none_ of the payment gateways I've tested have the Payment Method reported in notification emails, due to a bug in WP eCommerce. I've just raised an issue on that project:

https://github.com/wp-e-commerce/WP-e-Commerce/issues/2152

You can install this plugin for a temporary fix until that issue is resolved and released:

https://gist.github.com/webaware/4635d476e506c95c26c66a121631a7dc

**Comment by ablears** [comment]
Great - thank you!
